import requests
import pandas as pd
import yfinance as yf
import logging
import config

logger = logging.getLogger(__name__)

TWELVEDATA_LIMIT_REACHED = False


def normalize_symbol(symbol: str) -> str:
    """Normalizes input symbols (e.g., 'XAUUSD' -> 'XAU/USD', 'eurusd' -> 'EUR/USD')."""
    s = symbol.upper().strip()
    if s in ["XAUUSD", "GOLD", "XAU-USD"]:
        return "XAU/USD"
    if len(s) == 6 and not s.endswith("USDT") and "/" not in s:
        return f"{s[:3]}/{s[3:]}"
    return s


def get_data_binance(symbol: str, interval: str, limit: int = 500):
    try:
        url = f"https://api.binance.com/api/v3/klines?symbol={symbol}&interval={interval}&limit={limit}"
        res = requests.get(url, timeout=10)
        if res.status_code == 200:
            data = res.json()
            df = pd.DataFrame(data, columns=[
                'time', 'open', 'high', 'low', 'close', 'volume',
                'close_time', 'qav', 'num_trades', 'taker_base_vol', 'taker_quote_vol', 'ignore'
            ])
            df['time'] = pd.to_datetime(df['time'], unit='ms')
            for col in ['open', 'high', 'low', 'close', 'volume']:
                df[col] = df[col].astype(float)
            return df[['time', 'open', 'high', 'low', 'close', 'volume']]
    except Exception as e:
        logger.error(f"Binance fetch error for {symbol}: {e}")
    return None


def get_data_twelvedata(symbol: str, interval: str, limit: int = 500):
    global TWELVEDATA_LIMIT_REACHED

    if TWELVEDATA_LIMIT_REACHED:
        return None

    api_key = getattr(config, "TWELVEDATA_API_KEY", "")
    if not api_key:
        return None

    url = f"https://api.twelvedata.com/time_series?symbol={symbol}&interval={interval}&outputsize={limit}&apikey={api_key}"
    try:
        res = requests.get(url, timeout=10)
        json_data = res.json()

        if res.status_code == 200 and "values" in json_data:
            df = pd.DataFrame(json_data["values"])
            df["time"] = pd.to_datetime(df["datetime"])
            for col in ["open", "high", "low", "close", "volume"]:
                df[col] = df[col].astype(float) if col in df.columns else 0.0
            df = df.sort_values("time").reset_index(drop=True)
            return df[["time", "open", "high", "low", "close", "volume"]]

        if json_data.get("code") == 429 or "api key" in str(json_data.get("message")).lower():
            logger.warning("⚠️ TwelveData limit reached! Switching to Yahoo Finance Fallback.")
            TWELVEDATA_LIMIT_REACHED = True

    except Exception as e:
        logger.error(f"TwelveData error for {symbol}: {e}")

    return None


def fetch_yf_dataframe(yf_symbol: str, interval: str):
    """Robust helper to fetch and clean yfinance dataframe."""
    try:
        yf_interval = "1m" if interval in ["1m", "1min"] else "15m"
        period = "1d" if yf_interval == "1m" else "5d"

        df = yf.download(yf_symbol, period=period, interval=yf_interval, progress=False)
        if df is not None and not df.empty:
            df = df.reset_index()
            
            # Clean MultiIndex columns if generated by recent yfinance releases
            if isinstance(df.columns, pd.MultiIndex):
                df.columns = [col[0] for col in df.columns]

            time_col = "Datetime" if "Datetime" in df.columns else "Date"
            if time_col in df.columns:
                df = df.rename(columns={
                    time_col: "time",
                    "Open": "open",
                    "High": "high",
                    "Low": "low",
                    "Close": "close",
                    "Volume": "volume"
                })
                df["time"] = pd.to_datetime(df["time"]).dt.tz_localize(None)
                return df[["time", "open", "high", "low", "close", "volume"]]
    except Exception as e:
        logger.error(f"yfinance download error for {yf_symbol}: {e}")
    return None


def get_data_yfinance(symbol: str, interval: str = "1m"):
    """Multi-ticker fallback for Gold & Forex."""
    yf_symbol_map = {
        "BTCUSDT": "BTC-USD",
        "ETHUSDT": "ETH-USD",
        "SOLUSDT": "SOL-USD",
    }

    if symbol in yf_symbol_map:
        primary_ticker = yf_symbol_map[symbol]
        secondary_ticker = None
    elif symbol == "XAU/USD":
        primary_ticker = "XAUUSD=X"
        secondary_ticker = "GC=F"
    elif "/" in symbol:
        primary_ticker = symbol.replace("/", "") + "=X"
        secondary_ticker = None
    else:
        primary_ticker = symbol
        secondary_ticker = None

    # Attempt 1: Primary Ticker
    df = fetch_yf_dataframe(primary_ticker, interval)
    if df is not None and not df.empty:
        return df

    # Attempt 2: Secondary Ticker (Gold Backup)
    if secondary_ticker:
        logger.info(f"Primary ticker {primary_ticker} failed, trying backup {secondary_ticker}...")
        df = fetch_yf_dataframe(secondary_ticker, interval)
        if df is not None and not df.empty:
            return df

    return None


def get_data(symbol: str):
    """Main router with multi-tier failover."""
    symbol = normalize_symbol(symbol)
    
    entry_tf_binance = getattr(config, "ENTRY_INTERVAL_BINANCE", "1m")
    trend_tf_binance = getattr(config, "TREND_INTERVAL_BINANCE", "15m")
    entry_tf_td = getattr(config, "ENTRY_INTERVAL_TWELVEDATA", "1min")
    trend_tf_td = getattr(config, "TREND_INTERVAL_TWELVEDATA", "15min")

    # Crypto check
    if any(crypto in symbol for crypto in ["USDT", "BTC", "ETH", "SOL"]):
        entry_df = get_data_binance(symbol, entry_tf_binance)
        trend_df = get_data_binance(symbol, trend_tf_binance)
        if entry_df is not None and trend_df is not None:
            return entry_df, trend_df

    # Forex & Gold Tier 1: TwelveData
    entry_df = get_data_twelvedata(symbol, entry_tf_td)
    trend_df = get_data_twelvedata(symbol, trend_tf_td)

    # Forex & Gold Tier 2: Yahoo Finance Fallback
    if entry_df is None or entry_df.empty or trend_df is None or trend_df.empty:
        logger.info(f"🔄 Fetching {symbol} via Yahoo Finance Fallback...")
        entry_df = get_data_yfinance(symbol, interval="1m")
        trend_df = get_data_yfinance(symbol, interval="15m")

    return entry_df, trend_df
